apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-app
  namespace: my-namespace
  labels:
    app: spring-boot-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-boot-app
  template:
    metadata:
      labels:
        app: spring-boot-app
    spec:
      containers:
        - name: spring-boot-app
          image: 204367318498.dkr.ecr.ap-south-1.amazonaws.com/shyams/javamicroservice:__TAG__
          ports:
            - containerPort: 8080
