name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  AWS_REGION: ap-south-1
  ECR_REGISTRY: 204367318498.dkr.ecr.ap-south-1.amazonaws.com
  ECR_REPOSITORY: shyams/javamicroservice

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build JAR
      run: mvn clean package

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Get short SHA for Docker tag
      id: get_sha
      run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build Docker image with dynamic tag
      run: |
        IMAGE_TAG=$ECR_REGISTRY/$ECR_REPOSITORY:$SHORT_SHA
        docker build -t $IMAGE_TAG .

    - name: Push Docker image to ECR
      run: |
        IMAGE_TAG=$ECR_REGISTRY/$ECR_REPOSITORY:$SHORT_SHA
        docker push $IMAGE_TAG

    - name: Output ECR image tag
      run: echo "✅ Docker image pushed to: $ECR_REGISTRY/$ECR_REPOSITORY:$SHORT_SHA"

   
